services:
  - type: web
    name: gerot-dashboard
    env: docker
    plan: standard
    region: oregon
    dockerfilePath: Dockerfile
    numInstances: 1
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: MS_TENANT_ID
        value: ""
      - key: MS_CLIENT_ID
        value: ""
      - key: MS_CLIENT_SECRET
        value: ""
      - key: MS_PLANNER_PLAN_ID
        value: ""
      - key: MS_PLANNER_BUCKET_ID
        value: ""

      # Segredos NÃO devem ser versionados. Configure no painel do Render.
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false

      - key: USE_TAILWIND_THEME
        value: "true"
